<?php

/**
 * Konnex Integrations IntelliFlo Leads API
 * <p>A simple API that wraps the IntelliFlo Leads API.</p><p>NOTE: In order to use this Integrations API, users must have a paid IntelliFlo subscription and an active Tenant ID for OAuth2 Authentication. <p>For further information please refer to the <a href=\"https://developer.intelliflo.com\">IntelliFlo Developer Documentation</a>.</p>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@konnex-engine.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > swagger-codegen/modules/swagger-codegen/src/main/resources/php-laravel/
 */


Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->describe('Display an inspiring quote');