<?php

/**
 * Konnex Addresses API
 * An API that allows for creating, reading, updating and deleting of Konnex User Address data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@konnex-engine.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > swagger-codegen/modules/swagger-codegen/src/main/resources/php-laravel/
 */


namespace KonnexEngine\Http\Controllers;

use Illuminate\Support\Facades\Request;

class AddressesController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createLeadAddress
     *
     * Creates a new Address.
     *
     * @param int $leadID The leadID of the Lead to get addresses for (required)
     *
     * @return Http response
     */
    public function createLeadAddress($leadID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing createLeadAddress as a post method ?');
    }
    /**
     * Operation getLeadAddresses
     *
     * Retrieves all available Konnex User address data.
     *
     * @param int $leadID The leadID of the Lead to get addresses for (required)
     *
     * @return Http response
     */
    public function getLeadAddresses($leadID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getLeadAddresses as a get method ?');
    }
    /**
     * Operation deleteLeadAddress
     *
     * Delete address data..
     *
     * @param int $leadID The leadID of the Lead to get addresses for (required)
     * @param int $addressID The address ID for the specific address to delete. (required)
     *
     * @return Http response
     */
    public function deleteLeadAddress($leadID, $addressID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteLeadAddress as a delete method ?');
    }
    /**
     * Operation getLeadAddressByID
     *
     * Returns a specific Address by ID.
     *
     * @param int $leadID The leadID of the Lead to get addresses for (required)
     * @param int $addressID The Address ID for the specific Address. (required)
     *
     * @return Http response
     */
    public function getLeadAddressByID($leadID, $addressID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getLeadAddressByID as a get method ?');
    }
    /**
     * Operation updateLeadAddress
     *
     * Update address data..
     *
     * @param int $leadID The leadID of the Lead to get addresses for (required)
     * @param int $addressID The Address ID for the specific Address. (required)
     *
     * @return Http response
     */
    public function updateLeadAddress($leadID, $addressID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateLeadAddress as a put method ?');
    }
}
